# Uses the official PyTorch image with ROCm support for GPU acceleration
# This image includes PyTorch, CUDA, and necessary libraries for GPU-based OCR processing.
# Notes: 
#   -Ensure that your host system has compatible AMD GPUs and ROCm drivers installed to utilize this image effectively.
#   -This will highly increase the image size compared to a slim Python image (+30GB), but it is necessary for GPU support in OCR tasks.

FROM rocm/pytorch:latest

# Set environment variables to prevent Python from writing .pyc files and to ensure output is flushed immediately
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install necessary system dependencies for Django, PostgreSQL, and OCR processing
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    cmake \
    g++ \
    git \
    tesseract-ocr \
    && rm -rf /var/lib/apt/lists/*

# Necessary for face_recognition and dlib
RUN pip install --no-cache-dir setuptools==70.0.0

COPY requirements.txt requirements-worker.txt /app/
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir -r requirements-worker.txt

COPY . /app/